version: "3"

services:

  unimus-db:
    image: mariadb
    container_name: unimus-db
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=unimus
      - MYSQL_USER=unimus
      - MYSQL_PASSWORD=secret
    volumes:
      - ./db:/var/lib/mysql
      
  unimus:
    image: croc/unimus:v1.1.0
    container_name: unimus
    depends_on:
      - unimus-db
    ports:
      - "8085:8085"
    volumes:
      - ./config:/etc/unimus
    entrypoint:
      - /opt/start.sh

