version: "3"

services:
  db:
    image: mariadb
    command: --max_allowed_packet=268M
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=unimus
      - MYSQL_USER=unimus
      - MYSQL_PASSWORD=secret
      #- TZ=Europe/Budapest
    volumes:
      - './db:/var/lib/mysql'
      - '/etc/localtime:/etc/localtime:ro'
    restart: unless-stopped
  unimus:
    image: croc/unimus
    environment:
      # base memory params for java
      #- XMX=1024M
      #- XMS=256M
      # OR more customizable JAVA options
      - JAVA_OPTS=-Xms256M -Xmx1024M
      - TZ=Europe/Budapest
    volumes:
      - './config:/etc/unimus'
      #- '/etc/localtime:/etc/localtime:ro'
    depends_on:
      - db
    ports:
      - '8085:8085'
#      - '5509:5509' # for unimus-core connection if the unimus version is higher than 2.0.0
    restart: unless-stopped
