version: "3"

services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=unimus
      - MYSQL_USER=unimus
      - MYSQL_PASSWORD=secret
      #- TZ=Europe/Budapest
    volumes:
      - './db:/var/lib/mysql'
      - '/etc/localtime:/etc/localtime:ro'
    restart: unless-stopped
  unimus:
    image: croc/unimus:dev
    environment:
      # base memory params for java
      - XMX=1024M
      - XMS=256M
      # OR more customizable JAVA options
#      - JAVA_OPTS=-Xms128M -Xmx512M
      - TZ=Europe/Budapest
    volumes:
      - './config:/etc/unimus'
      #- '/etc/localtime:/etc/localtime:ro'
    depends_on:
      - db
    ports:
      - '8085:8085'
      - '5509:5509'
    restart: unless-stopped
