apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unimus.fullname" . }}
  labels:
    {{- include "unimus.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "unimus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "unimus.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "unimus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ .Chart.Name }}-config
          emptyDir: {}
        - name: {{ .Chart.Name }}-log
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JAVA_OPTS
              value: {{ .Values.unimus.JAVA_OPTS }}
            - name: TZ
              value: {{ .Values.unimus.TZ }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }} 
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.kubernetes.checkdelay_livenes }}
            timeoutSeconds: {{ .Values.kubernetes.timeout }}
            httpGet:
              path: /
              port: {{ .Values.service.port }} 
          readinessProbe:
            initialDelaySeconds: {{ .Values.kubernetes.checkdelay_readiness }}
            timeoutSeconds: {{ .Values.kubernetes.timeout }}
            httpGet:
              path: /
              port: {{ .Values.service.port }}
          volumeMounts:
            - name: {{ .Chart.Name }}-config 
              mountPath: /etc/unimus
            - name: {{ .Chart.Name }}-log
              mountPath: /var/log/unimus
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
