apiVersion: v1
kind: Service
metadata:
  name: {{ include "unimus.fullname" . }}
  labels:
    {{- include "unimus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }} 
      protocol: TCP
      name: http
  selector:
    {{- include "unimus.selectorLabels" . | nindent 4 }}
