# This is a basic workflow to help you get started with Actions

name: Auto-CI-dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
#  push:
#    branches: [ "dev" ]
#  pull_request:
#    branches: [ "dev" ]
  # schedule:
  #   # UTC time 3:00 = 5:00 CET
  #   - cron: '19 3 * * *' # every Sunday at 5:00

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-amd64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: build image - AMD64
        run: |
          docker build --rm -t accuris-infrastructure/unimus . || { echo "docker image build failed - amd64"; exit 1; }
          docker tag accuris-infrastructure/unimus ghcr.io/accuris-infrastructure/unimus:dev
          docker images accuris-infrastructure/unimus
      - name: push container
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
        run: |
          docker images
          echo $CR_PAT | docker login ghcr.io -u accuris-infrastructure --password-stdin
          docker images | grep -i unimus
          docker push ghcr.io/accuris-infrastructure/unimus:dev
  build-arm64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: dev
      # buildx with quemu
      - name: qemu setup for buildx for arm build
        uses: docker/setup-qemu-action@v2
      - name: setup buildx for arm build
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: build image - ARM 64bit
        env:
          ARCH: ARM
        run: |
          echo "Buildx supported platforms: ${{ steps.buildx.outputs.platforms }}"
          docker build --rm --platform linux/arm64 -t accuris-infrastructure/unimus-arm64 . || { echo "docker image build failed - arm64"; exit 1; }
          docker tag accuris-infrastructure/unimus-arm64 ghcr.io/accuris-infrastructure/unimus-arm64:dev
          docker images accuris-infrastructure/unimus-arm64
      - name: push container
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
        run: |
          docker images
          echo $CR_PAT | docker login ghcr.io -u accuris-infrastructure --password-stdin
          docker images | grep -i unimus-arm64
          docker push ghcr.io/accuris-infrastructure/unimus-arm64:dev

